### ISSUE TITLE
Add user class

### ISSUE THREAD

**Issue by alpha-tango** [goobers/themenu#11]
(and team?)

**Comment by scottstanie** [comment]
- [x] https://github.com/scottstanie/codenames/blob/master/codenames/urls.py#L27-L29 urls from django-registration
- [x] Add templates for login, logout
- [ ] Add an owner (list of owners?) to calendars
- [ ] Add checks to make sure the one checking off "prepared" or "eaten" is the one of the owners of the calendar
- [ ] Make the edit of a meal only available to owner of calendar
- [x] Add a profile? Idk what we want on a profile
- [ ] Figure out if a user should be connected with...
  - a Dish
  - a Source of a dish
  - the Notes on a dish (if me and christine make a dish that shari makes, should we be able to add our own notes/ addendums to the dish?)
  - Possibly something with the tags (I want to look up what I make every christmas. how do i make that separate from christines "christmas" tag?
