### ISSUE TITLE
Tag create/update: Do we want the colors to be choices? or is a textbox fine?

### ISSUE THREAD

**Issue by scottstanie** [goobers/themenu#36]
If so, forms.py would add something like this

class TagModelForm(forms.ModelForm):
    """Like a normal ModelForm, but the Many-to-Many fields
    use the prettier select2 multiple fields"""
    class Meta:
        model = Tag
        fields = ['name', 'color']

        widgets = {
            'color': NameSelect2Widget
        }

**Comment by alpha-tango** [comment]
I think the random color generator is fine for this, but happy to revisit that later (to do it Github-style maybe)
