### ISSUE TITLE
rebrand

### ISSUE THREAD

**Issue by alpha-tango** [goobers/themenu#64]
+ domain purchase

**Comment by alpha-tango** [comment]
nomplan.life!

**Comment by alpha-tango** [comment]
Avocado:
![avocado_logo](https://user-images.githubusercontent.com/8017149/27111346-887b2b9c-507d-11e7-8fac-55f4c9cd3f58.jpg)
Calendar:
![calendar_logo](https://user-images.githubusercontent.com/8017149/27111350-8e0de11c-507d-11e7-99b3-ee0374936b78.jpg)
Saucy pan:
![saucy_pan_logo](https://user-images.githubusercontent.com/8017149/27111355-928d937c-507d-11e7-9266-d3afdda8a81e.jpg)

**Comment by alpha-tango** [comment]
Pingey versions:
![avocado_logo](https://user-images.githubusercontent.com/8017149/27111607-537e4a80-507f-11e7-980e-b4f574b0a7db.png)
![calendar_logo](https://user-images.githubusercontent.com/8017149/27111610-57c69cf0-507f-11e7-8f99-2913e976891c.png)
![saucy_pan_logo](https://user-images.githubusercontent.com/8017149/27111615-5c00347a-507f-11e7-9206-5208b8a25dc5.png)

**Comment by scottstanie** [comment]
"Include the following code in the head of your HTML document."
```html
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
```

**Comment by alpha-tango** [comment]
Here's a square picture of a round pan:
![saucy_pan_logo square](https://user-images.githubusercontent.com/8017149/27111804-96cd63d8-5080-11e7-9058-e4e9372d83ee.png)

**Comment by scottstanie** [comment]
s3 link: https://s3.amazonaws.com/nom-plan/avocado.png
cloundfront: https://d2fcjrtizqatsy.cloudfront.net/avocado.png
#71

**Comment by alpha-tango** [comment]
unnecessary pictures for calendar view:
![breakfast](https://user-images.githubusercontent.com/8017149/27112760-05fe9fbe-5087-11e7-8341-87e714831a72.png)
![lunch](https://user-images.githubusercontent.com/8017149/27112763-0b9e29c6-5087-11e7-9c49-357d694b2ba2.png)
![dinner](https://user-images.githubusercontent.com/8017149/27112766-0fed3878-5087-11e7-9072-3bb2c4a73199.png)
![dessert](https://user-images.githubusercontent.com/8017149/27112775-16b15806-5087-11e7-963a-fa8873ca5d29.png)
